reference: 'transcriptome' # genome or transcriptome
center: 'A'
nt: 4
featurenum: 5
buffersize: 1000
labeltype: 'I'
ref_dump_position: "memory"
device: 'CPU'
batch_size: 10000
model: 'general'
coverage_cutoff: 5
ratio_cutoff: 0
filter_snp: 'False'
filter_m6A: 'False'
in_alu_coverage: 10
out_alu_coverage: 30
in_alu_ratio: 0.1
out_alu_ratio: 0.3
add_m6A_reference: 'False'