channels:
  - conda-forge
  - bioconda
  - bioconda/label/cf201901
  - anaconda
dependencies:
  - python =3.6
  - samtools =1.12
  - minimap2 =2.20
  - nanopolish =0.13.2
  - htslib =1.12
  - nanofilt =2.8.0
  - snakemake =6.12.3
  - h5py=2.10.0
  - bedtools=2.30.0
  - pysam=0.17.0
  - scipy=1.5.3
  - numpy=1.18.5
  - statsmodels=0.11.1
  - pybigwig=0.3.18
  - fastqsplitter=1.2.0
  - seqtk=1.3
  - keras=2.2.4
  - keras-preprocessing=1.1.0
  - tensorflow=1.12.0
  - tensorflow-gpu=1.12.0
  - six=1.15.0
  - bioawk=1.0
  - perl=5.32.1
  - gawk=5.1.0
  - smart_open=3.0
