channels:
  - conda-forge
  - bioconda
  - bioconda/label/cf201901
dependencies:
  - python =3.6
  - samtools =1.12
  - minimap2 =2.20
  - nanopolish =0.13.2
  - htslib =1.12
  - nanofilt =2.8.0
  - snakemake =6.12.3
  - h5py=2.10.0
  - pysam=0.16.0.1
  - scipy=1.5.3
  - numpy=1.18.5
  - statsmodels=0.11.1
