#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --nodes=1 --ntasks-per-node=1
#SBATCH --account=PCON0009
module load python/3.6-conda5.2
source activate AIediting

mkdir intermediates
cd intermediates
mkdir fastq/
mkdir fast5/
mkdir summary/
mkdir reference/
ln -s /fs/project/PCON0009/LabData/Human/H1-hESC/Transcriptome/ONT/directRNA/GT20-02070_HSC-1_RNA_F_R1/fastq_pass fastq/H1-hESC
ln -s /fs/project/PCON0009/LabData/Human/H1-hESC/Transcriptome/ONT/directRNA/GT20-02070_HSC-1_RNA_F_R1/fast5_pass fast5/H1-hESC
ln -s /fs/project/PCON0009/LabData/Human/H1-hESC/Transcriptome/ONT/directRNA/GT20-02070_HSC-1_RNA_F_R1/sequencing_summary_FAL42026_033d8d92.txt summary/H1-hESC_summary.txt
ln -s /fs/project/PCON0009/Au-scratch2/haoran/reference/genecode/GRCh38.primary_assembly.genome.fa reference/genome.fa
cd ../


snakemake -c 336 -p outputs/H1-hESC_fast5_list.txt --cluster "sbatch -A PCON0009 -t {resources.runtime} -N 1 -c {threads}" --jobs 12 --set-scatter split=12
